---
- name: Update apt cache and install essential tools
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes

- name: Set up official GPG Docker Key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download official GPG Key
  ansible.builtin.get_url:
    url: "{{ docker_repo_url }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add official Docker Repository in APT Sources
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }} 
      {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker

- name: Install Docker Engine, CLI, Containerd and Docker Compose Plugin
  ansible.builtin.apt:
      name: "{{ docker_packages }}"
      state: present
      update_cache: yes

- name: Assure Docker service is active and enabled in systemd
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Add non-root EC2 user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes