---
- name: Update apt cache and install essential tools
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes

- name: Set up official GPG Docker key in Debian
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add official docker repository in APT sources
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian
      {{ ansible_facts['distribution_release'] }} stable
    state: present
    filename: docker

- name: Install Docker Engine, CLI, Containerd and Docker Compose Plugin
  ansible.builtin.apt:
      name: "{{ docker_packages }}"
      state: present
      update_cache: yes

- name: Assure docker service is active and enabled in systemd
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Add non-root EC2 user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user | default(system_user) }}"
    groups: docker
    append: yes