---
docker_repo_url: "{{ 'https://download.docker.com/linux/ubuntu' if ansible_distribution == 'Ubuntu' else 'https://download.docker.com/linux/debian' }}"

base_packages:
  - ca-certificates
  - curl
  - gnupg
  - git
  - unzip

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin