name: "Terraform AWS"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./iac/terraform/

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::593710895387:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Install Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.x"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_aws_region: "us-east-1"
          TF_VAR_environment: "iftech"
          TF_VAR_tfstate_bucket_name: "iftech-terraform-state-app"
          TF_VAR_admin_public_ip: ${{ secrets.ADMIN_PUBLIC_IP }}
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_aws_region: "us-east-1"
          TF_VAR_environment: "iftech"
          TF_VAR_tfstate_bucket_name: "iftech-terraform-state-app"
          TF_VAR_admin_public_ip: ${{ secrets.ADMIN_PUBLIC_IP }}
        run: terraform apply -auto-approve -no-color